apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-14504
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp-sa-14504
      containers:
      - name: webapp
        image: selva14504/my-python-app
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: webapp-config-14504
        - secretRef:
            name: webapp-secret-14504
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: webapp-pvc

