apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-rolebinding-14504
subjects:
- kind: ServiceAccount
  name: webapp-sa-14504
roleRef:
  kind: Role
  name: webapp-role-14504
  apiGroup: rbac.authorization.k8s.io

